### ISSUE TITLE
make cookbook solr5 ready

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-solrcloud#27]
bunch of references, but not necessary

https://cwiki.apache.org/confluence/display/solr/Upgrading+a+Solr+4.x+Cluster+to+Solr+5.0
https://cwiki.apache.org/confluence/display/solr/Taking+Solr+to+Production
https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5
http://lucene.apache.org/solr/5_0_0/changes/Changes.html
https://s.apache.org/Solr-Ref-Guide-PDF

**Comment by tjordahl** [comment]
This would be very helpful as it seems like the current recipe does not work.

**Comment by vkhatri** [comment]
@tjordahl i will take a stab at it this weekend

**Comment by vkhatri** [comment]
@tjordahl how about trying it now? cookbook now supports v5

**Comment by vkhatri** [comment]
solr5 support added.
