### ISSUE TITLE
Could not find configName for collection samplecollection found:null

### ISSUE THREAD

**Issue by sameronline** [vkhatri/chef-solrcloud#28]
When I deploys SolrCloud using your book and example below, i ge tthe following error when i try to add a new core through the interface 
- http://192.168.50.5:8080/solr/#/~cores 
- screenshot: http://screencast.com/t/KBWPMsHPVG
- Error CREATEing SolrCore 'new_core': Unable to create core [new_core] Caused by: Could not find configName for collection samplecollection found:null

No matter what i try it seems that SolrCloud is not connecting to the zookeeper

##Single Node SolrCloud Test Cluster Deployment
```json
"default_attributes": {
  "solrcloud": {
    "zk_run": true,
    "port": "8080",
    "setup_user": true,
    "manager": true,
    "zkconfigsets": {
      "samplecollection": {}
    },
    "collections": {
      "samplecollection": {
        "collection_config_name": "samplecollection"
      }
    }
  }
}
```

**Comment by vkhatri** [comment]
@sameronline i will give it a shot tomorrow

i assume you have already checked it, but do you config set `samplecollection` in zookeeper? is solr able to register with zookeeper?

**Comment by sameronline** [comment]
@vkhatri  thanks for your response.

Sorry i'm pretty new to zookeeper, How do i check if i have a samplecollection in zookeeper? i'm assuming that zk_run: true runs Solr internal zookeeper server etc..

**Comment by sameronline** [comment]
@vkhatri , Ok after some debugging, i found out there was an issue sending configs to zookeeper, it requires files/default/samplecollection to files/default/samplecollection/conf

Now i get this error on vagrant provision:

 "org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException:Error CREATEing SolrCore 'samplecollection_shard1_replica1': Unable to create core [samplecollection_shard1_replica1] Caused by: /samplecollection/tlog" 

Not sure what does this mean.

**Comment by vkhatri** [comment]
@sameronline sorry for the delay, i will give it a shot today.

**Comment by vkhatri** [comment]
@sameronline were you able to resolve this error, i could not reproduce this error on my setup.
