### ISSUE TITLE
solrcloud should not unconditionally install tool chain (gcc, patch)

### ISSUE THREAD

**Issue by tjordahl** [vkhatri/chef-solrcloud#29]
In our environment, we do not allow compilers to be installed on our VMs.  So we package the zookeeper gems in to an RPM and install that before any dependencies (like zk).

Please add an attribute to prevent the following code from executing in tarball.rb:

    # Require for zk gem
    %w(patch gcc).each do |pkg|
      package pkg do
        action :nothing
      end.run_action(:install)
    end

**Comment by vkhatri** [comment]
@tjordahl in that case `chef_gem 'zk'` resource would also become obsolete. correct?

**Comment by tjordahl** [comment]
Our strategy is to install the compiled dependencies for the gem in an RPM and not the gem itself, but that is just how we go about it.  That attribute is great, thanks!
