### ISSUE TITLE
Attribute 'configset_name' is not used in 'zkconfigset' provider

### ISSUE THREAD

**Issue by gdud** [vkhatri/chef-solrcloud#30]
In *zkconfigset* provider **name** attribute is used, insted of **configset_name**, as value of *-configname* paramerter passed to zkcli.

It can be useful to put configuration under different name into zookeeper. Especially in a case, when you have nested directory structure in cookbook files, for example /files/default/solr_config/[CONFIGNAME], and you want to avoid to create similar structure in zookeeper (configs/solr_config/[CONFIGNAME]).

**Comment by vkhatri** [comment]
@gdud will check it today!

**Comment by vkhatri** [comment]
@gdud  thanks for the PR!  i think it is better if we keep just one attribute - `new_resource.configset_name` instead of using `new_resource.name` in providers `zkconfigset`.

will work on it.
