### ISSUE TITLE
bump solr version to 5.2.1

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-solrcloud#37]

**Comment by vkhatri** [comment]
looks like jetty9 is causing trouble for solr init service for v5.2.x:

https://archive.apache.org/dist/lucene/solr/5.2.1/changes/Changes.html#v5.2.0.upgrading_from_solr_5.1

`It is no longer possible to run "java -jar start.jar" from inside the server directory. The bin/solr script is the only supported way to run Solr. This is necessary to support HTTP and HTTPS modules in Jetty which can be selectively enabled by the bin/solr scripts. In case you have a pressing need to run solr the old way, you can run "java -jar start.jar --module=http" to get the same behavior as before. `

need to check whether require other changes (worth looking into bin/solr) or `--module=http` is sufficient.

**Comment by sylvainsf** [comment]
Heh I started work on this Friday as well! Anything I can do to help?

**Comment by vkhatri** [comment]
@sylvainsf thank you, really appreciate it.

what i gathered so far is that, new directory structure seems to be broken in `v5.2.x` and attributes needs to be modified accordingly, like `jetty_home`.

jetty 9 seems to be using different `jetty*xml` file for different module (got it from start.jar --help, need to check new init script).

And one major change is new sysv `init` style, i think its better to update the cookbook with it for `>v5.2.x`. keeping the attributes is always a challenge and there are significant changes in `v5.2`

i will start creating individual issues and perhaps i can spend this weekend on it.

**Comment by sylvainsf** [comment]
Yes I quickly found there was a LOT that would need to change. In the interim I've created some recipes for starting/restarting via the solr command instead of init.d but this is less optimal because after a system restart it would not start solr until the next scheduled chef run.

**Comment by kiwimanman** [comment]
Was looking into helping write new init.d's from the provided config in the new 5.2.x tarball and integrate the various node attributes in. I think I have had decent success so far but went to try and test the changes and couldn't get kitchen to converge.

Specifically ubuntu 12.04 errors when the java cookbook installs curl due to some really out of date default urls in apt-get. Also noticed the actual specs are real light.

Is there something special you do to get kitchen up or to test in general? Other than this part I think I have the new blessed path for init.d pretty close to working and would love to submit them for review.

**Comment by vkhatri** [comment]
@kiwimanman i am with you for specs to be minimal for this cookbook. i am planning to add once cookbook is v5.2.x ready.

the issue you are facing might be due to outdated `apt-get update`. i have updated `.kitchen.yml`. thanks for reporting this!

good to hear that you got new `sysv init` working, i have not gotten much time to finish it. but, i think we would have to modify it in favor of  leveraging `/etc/default/solr`.

i just committed few changes and opened #46 to add more specs.

**Comment by kiwimanman** [comment]
Whew, a little more work than I was expecting but I believe that should do it. 5.2.x it seems changed a lot about how the ```/etc/default/solr``` file worked but I believe the way I did it should be backwards compatible.
