### ISSUE TITLE
gh-pages outdated

### ISSUE THREAD

**Issue by slobo** [vkhatri/chef-solrcloud#41]
I almost looked away from the project since on http://vkhatri.github.io/chef-solrcloud/ it doesn't mention Solr 5 support. 
Consider updating gh-pages or setting https://supermarket.chef.io/cookbooks/solrcloud as the project home page and getting rid of gh page.
Thanks

**Comment by vkhatri** [comment]
@slobo  i think we can set supermarket as project home page.

thanks! updated gh pages anyways.
