### ISSUE TITLE
fix kitchen test

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-solrcloud#45]
- kitchen test is broken for `debian` family, need to add apt-get update
- add few more configuration parameters to .kitchen.yml
- add port mapping 8888 -> 8983

**Comment by vkhatri** [comment]
@kiwimanman let me know if kitchen test is working now.

leaving it open for now.

**Comment by kiwimanman** [comment]
I thought it would copy my comment in here. To restate it, what is the need for the ```chef/``` prefix on the server list? When I deleted that everything worked fine.

**Comment by vkhatri** [comment]
@kiwimanman strange, not sure why it did not work for you and works just fine for me.

i have used these images in past, we can keep all the variants and let user choose for kitchen test. 

IMHO, most of the times folks just test with `ubuntu` or `centos` unless making changes to the cookbook. what do you think?

```
$ vagrant box list
chef/centos-6.5    (virtualbox, 1.0.0)
chef/ubuntu-12.04  (virtualbox, 0)
chef/ubuntu-14.04  (virtualbox, 1.0.0)
```

**Comment by vkhatri** [comment]
@kiwimanman if this sounds good to you, could you re base the PR?

**Comment by kiwimanman** [comment]
So I discovered my vagrant version was way behind, leading to the inability to find the chef/ prefixed hosts.

Since this is a cookbook using the chef ones is probably the right thing to do. Just took a while to figure out my issue.

I rebased the PR. Close or not depending on what you think is best.

**Comment by vkhatri** [comment]
@kiwimanman thanks for patching the PR for this one!
