### ISSUE TITLE
Issues with setting default['solrcloud']['version'] and wrapper cookook. 

### ISSUE THREAD

**Issue by rmldsky** [vkhatri/chef-solrcloud#58]
Hi,
I have a [wrapper](https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/) cookbook which uses yours. Unfortunately setting `default['solrcloud']['version']` in my cookbook works only partially. I uses it some places, like setting filenames and directories, but ie. when fetching .tgz from source it does not use it in creating URL string.

It works better when I use it within environment file to set attribute with version. Then it downloads and installs the desired version, but on the other hand fails to use the correct `init` script from cookbook (the if on ` > 5.2` fails)

Oh, I am trying to install solr 5.2.1, not sure if this is even fully supported by your cookbook, thou I have seen a lot of references in the codebase so I am giving it a try.

**Comment by vkhatri** [comment]
there are still some pending tasks for `5.2.x`. but, last time i checked cookbook was working for `5.2.1`. i am planning to complete the pending tasks this week.

let me test it with a wrapper cookbook for the `version` issue.

**Comment by rmldsky** [comment]
On a side note, I have also tried with a default version being `5.1.0` and it also takes the obsolete init.d file. Seems now solr provides the `install_solr_service.sh` which installs solr as a service on Linux systems. It sets up nicely all the directories and parameters in `solr.in.sh`

**Comment by kiwimanman** [comment]
Huh, here is an article that explains exactly what is going on and why the kitchen suite does not capture it. TLDR; Compile time dependencies get fixed by environment changes like what kitchen does. https://christinemdraper.wordpress.com/2014/10/06/avoiding-the-possible-pitfalls-of-derived-attributes/

Looking through the attributes, derived values are used in many places. Should probably standardize on one method for handling them. It would seem to me the second one, using lazy evaluation, would work the best as it could allow for changes while still exposing the intended values meant to be used in each situation.

**Comment by kiwimanman** [comment]
I didn't see any movement on this issue and it is blocking us as well since we use a wrapping cookbook. Does this seem like a reasonable solution?

**Comment by vkhatri** [comment]
@kiwimanman sorry about that, i have been busy lately with $work. i see you PR, will check it out today. thanks!

**Comment by kiwimanman** [comment]
@vkhatri Does this seem like the way you want to go? More interested in getting consensus on code style direction than actually getting it merged.

**Comment by vkhatri** [comment]
@kiwimanman sorry for the delayed response. PR looks good to me and i know it will resolve the issues of attributes evaluation. but i am not certain about adding lazy attributes evaluation to the cookbook, i think there might be other options like moving the evaluated attributes to cookbook or perhaps write `LWRP/HWRP` for the installation.

i am going to give this issue another shot this weekend. thank you for your patience! really appreciate it.

attribute evaluation issue does not surface as long as cookbook is used with chef `Role` and `Environment` for attributes override and i must confess i have never tested the cookbook with another wrapper cookbook to do the setup. not sure if there is any anti pattern instructions that can be added to the cookbook that could prevent this issue to happen, something i hope to find this weekend.

let me know what do you think about it.

**Comment by kiwimanman** [comment]
No problem with the delay. If you look at @rmldsky 's first comment he links to a blog article on using wrapper cookbooks that came directly from the guys at chef. The wrapper or library cookbook pattern is definitely blessed and does make writing cookbooks usable by everyone a little (sometimes lot) harder.

I do think LWRP is the correct way to go, my concern is that this will not be backwards compatible. The reason I selected for my org to build against this was the install base (although I cannot find the numbers on supermarket anymore.) I worry you will end up supporting two internal ways to do the same thing vs two different external ones that need to be supported anyway. If you really want to do it cleanly my prediction is that it will become a major version bump.

**Comment by vkhatri** [comment]
@kiwimanman thank you for your feedback. there are other cookbook with the same pattern but does not suffer with this problem while using wrapper cookbook. i have started working on it and hope to arrive a conclusion soon.

i agree, LWRP is a major version bump and backward compatibility will be a major issue.

i will update soon, sorry for keeping you waiting.

**Comment by vkhatri** [comment]
@rmldsky @kiwimanman i made some changes to default attributes and tried setting `version` with `wrapper cookbook` and `role`, both methods worked for me.

i would admit that i have never tested the cookbook in past to change default attributes using wrapper cookbook, with role the attributes precedence works just fine but it does not always with the wrapper cookbook.

sorry for the long delay, i like to think that i did enough testing and this issue should be resolved by the recent changes. could you give the cookbook another shot and let me know if this works for you?

**Comment by rmldsky** [comment]
Cool! Will try to give it a look Today (or during the weekend) and report back! Thanks.

**Comment by vkhatri** [comment]
@rmldsky  @kiwimanman  did you get a chance to try out the new changes?

**Comment by vkhatri** [comment]
i will go ahead and close this one, please open another issue if issue still persists.
