### ISSUE TITLE
Installing dependencies for zk gem fail when apt-get update was not run first

### ISSUE THREAD

**Issue by rmldsky** [vkhatri/chef-solrcloud#59]
Installing dependencies like GCC or patch will fail on Ubuntu when apt-get update was not run first. This happened for me on a fresh EC2 instance. Unfortunately this cannot be satisfied by another cookbook/recipe as installation of this gem and dependencies happen just after cookbook compilation step in Chef. In most cases `include_recipe 'apt'` somewhere before the `package` reference helps.

Not sure how this behaves on non-Debian/Ubuntu Linux flavours.

```
# Require for zk gem
%w(patch gcc make).each do |pkg|
  package pkg do
    action :nothing
    only_if { node['solrcloud']['install_zk_gem'] }
  end.run_action(:install)
end
```

**Comment by vkhatri** [comment]
outdated `apt` is indeed a common issue, IMHO it is up to the user to keep `apt` updated as it impacts other chef resources or the system. I do not recall why `include 'apt'` is not yet added to the cookbook.

for kitchen test, cookbook `test/cookbooks/solrcloud_test/recipes/prerun.rb` runs `apt-get update`.

i am open for suggestions.

**Comment by rmldsky** [comment]
In the scenario when one is spawning a new instance on EC2 with `knife` and in the run list there is `solrcloud` cookbook it seems installing dependencies happen at the very beginning of chef run, thou it fails immediately. I did have this originally:

```
include_recipe 'apt'

package 'make' # when it was still missing from recipe, thanks for merging PR \o/

include_recipe 'solrcloud'
```
And it failed for me, as for some reason it tried to install dependencies first... clueless why it happened.

Any way I believe cookbooks should be self contained, and provide themselves means to run successfully. Currently without prior `apt-get update` cookbook will always fail and it depends on outside actions.

Great job on the cookbook and keep up the good work! :trophy:

**Comment by vkhatri** [comment]
@rmldsky thank you for your feedback!

i think adding `include 'apt'` does make sense and solves the problem. i have updated the cookbook.

`package 'make'` install will happen during converge phase, whereas cookbook `solrcloud` tries to install `chef_gem 'zk'` during compile phase which has a dependency of `make` package.
