### ISSUE TITLE
auto_system_memory / auto_java_memory seems backwards

### ISSUE THREAD

**Issue by randomstatistic** [vkhatri/chef-solrcloud#68]
I feel like these options encourage the misperception that you want your JVM heap to be as large as possible for Solr. You actually want something more the reverse, where your heap is a given number, and you leave the rest of the available ram to the system cache. (See http://wiki.apache.org/solr/SolrPerformanceProblems#RAM)

Obviously, auto_java_memory is a documented option, so it can't just be removed or changed at this point, but what I'd ideally want from something like this would be to use, say, 1/2 the available ram for heap (mainly to support vagrant and other non-production environments) up to a *maximum* of the set amount. 
Then you don't need to bother with an additional system memory parameter, and if you add RAM because your index grew, you don't need to change anything in your cookbook.

**Comment by vkhatri** [comment]
@randomstatistic agreed! to keep it simple i am thinking of:

- `default['solrcloud']['auto_java_memory'] = 'half'` will allocate half of the memory
- `default['solrcloud']['auto_java_memory'] = 'maximum'` will allocate max possible depending up on `default['solrcloud']['auto_system_memory']`
- if user is setting up `default['solrcloud']['java_xmx']` then skip `default['solrcloud']['java_xmx']`, similarly for `default['solrcloud']['java_xms']`
- if `node['memory']['total']` is > `32`, set `default['solrcloud']['java_xmx']` to `32g`

let me know what do you think about it.

**Comment by randomstatistic** [comment]
I like the idea of adding more named values as a way of preserving backwards compatibility while moving the meaning of the option a bit.

You're closer, but I probably still wouldn't use the values you're describing though. I try to figure out the minimum heap size my solr node needs for my collection/usage, and once I've done that, the only reason I'd ever want it to be any other value is because the node simply cannot support that value. Testing in vagrant would be the most likely example where my explicitly configured value might not be usable, but a lightweight QA node might be another.

I'm currently doing something like this, which I think would be generically useful:

```
desired_heap_mb = 12000
sys_memory_mb = (node['memory']['total'].gsub('kB', '').to_i / 1024).to_i
java_heap =
    if (sys_memory_mb > desired_heap_mb * 1.5)
        "#{desired_heap_mb}m"
    else
       "#{sys_memory_mb / 2}m" 
    end
override[:solrcloud][:auto_java_memory] = false
override[:solrcloud][:java_xmx] = java_heap
```

(Warning, I typed this, it's not syntax checked.)
So, if you can support the desired heap (with some headroom), use that and leave everything else to the system cache. Otherwise, scale down with system memory.

I think the elements are all there. Maybe `default['solrcloud']['auto_java_memory'] = 'minimum'` could mean this? `default['solrcloud']['auto_system_memory']` could replace the 1.5 multiplier I stuck in there, and `default['solrcloud']['java_xmx']` could replace desired_heap_mb?

**Comment by vkhatri** [comment]
That definitely sound a better approach. I admit that allocating maximum memory is not a best practice, but it is quite useful for low memory systems.

How about simply setting up `default['solrcloud']['java_xmx']` & `default['solrcloud']['java_xms']` to `(total memory) / 2)` by default and leave it up to the user to change. As it would differ among environments.

I can also think of using `e.g. 75%`, but that might not give the intended value for low memory systems.

I think that there is no generic default value for `default['solrcloud']['auto_system_memory']` & `default['solrcloud']['auto_system_memory']` and removing them keeps the cookbook simple.

But, let me know what are your final thoughts on it.

**Comment by randomstatistic** [comment]
Setting the heap with a default of 50% seems very reasonable to me. I very much agree that there's no generic default number anyone could pick here.
Removing the auto_system_memory certainly solves my somewhat pedantic issue, which is that it currently encourages the wrong settings. (specifically, maximizing heap instead of minimizing it) 

That said, it's still my belief that the configuration I described will almost always be what people really want. (That is, some value, or half available, if that value won't fit.) 
I think it would be convenient if the requested-vs-available check were in the cookbook, but I can certainly still keep this in my wrapper cookbook without much difficulty. 

Regardless, I appreciate your engagement on this. All things considered, it's a fairly minor issue.

**Comment by vkhatri** [comment]
@randomstatistic Thank you for the feedback. Will make the changes.

**Comment by vkhatri** [comment]
Cookbook updated.
